---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: database-1
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9377