apiVersion: v1
kind: Pod
metadata:
  name: nginx-service-pod
  namespace: my-gitops
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  namespace: my-gitops
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30007
